---
abstract: 'mt-aws/glacier - Perl Multithreaded Multipart sync to Amazon Glacier'
author:
  - 'Victor Efimov'
build_requires:
  DateTime: 0
  MIME::Base64: 3.11
  TAP::Harness: 0
  Test::Deep: 0
  Test::MockModule: 0
  Test::Spec: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-MtAws
provides:
  App::MtAws:
    file: lib/App/MtAws.pm
    version: 0.957
  App::MtAws::CheckLocalHashCommand:
    file: lib/App/MtAws/CheckLocalHashCommand.pm
    version: 0
  App::MtAws::ChildWorker:
    file: lib/App/MtAws/ChildWorker.pm
    version: 0
  App::MtAws::ConfigDefinition:
    file: lib/App/MtAws/ConfigDefinition.pm
    version: 0
  App::MtAws::ConfigEngine:
    file: lib/App/MtAws/ConfigEngine.pm
    version: 0
  App::MtAws::CreateVaultJob:
    file: lib/App/MtAws/CreateVaultJob.pm
    version: 0
  App::MtAws::DeleteVaultJob:
    file: lib/App/MtAws/DeleteVaultJob.pm
    version: 0
  App::MtAws::Exceptions:
    file: lib/App/MtAws/Exceptions.pm
    version: 0
  App::MtAws::FileCreateJob:
    file: lib/App/MtAws/FileCreateJob.pm
    version: 0
  App::MtAws::FileFinishJob:
    file: lib/App/MtAws/FileFinishJob.pm
    version: 0
  App::MtAws::FileListDeleteJob:
    file: lib/App/MtAws/FileListDeleteJob.pm
    version: 0
  App::MtAws::FileListRetrievalJob:
    file: lib/App/MtAws/FileListRetrievalJob.pm
    version: 0
  App::MtAws::FileUploadJob:
    file: lib/App/MtAws/FileUploadJob.pm
    version: 0
  App::MtAws::Filter:
    file: lib/App/MtAws/Filter.pm
    version: 0
  App::MtAws::ForkEngine:
    file: lib/App/MtAws/ForkEngine.pm
    version: 0
  App::MtAws::GlacierRequest:
    file: lib/App/MtAws/GlacierRequest.pm
    version: 0
  App::MtAws::InventoryDownloadJob:
    file: lib/App/MtAws/InventoryDownloadJob.pm
    version: 0
  App::MtAws::InventoryFetchJob:
    file: lib/App/MtAws/InventoryFetchJob.pm
    version: 0
  App::MtAws::Job:
    file: lib/App/MtAws/Job.pm
    version: 0
  App::MtAws::JobListProxy:
    file: lib/App/MtAws/JobListProxy.pm
    version: 0
  App::MtAws::JobProxy:
    file: lib/App/MtAws/JobProxy.pm
    version: 0
  App::MtAws::Journal:
    file: lib/App/MtAws/Journal.pm
    version: 0
  App::MtAws::LineProtocol:
    file: lib/App/MtAws/LineProtocol.pm
    version: 0
  App::MtAws::MetaData:
    file: lib/App/MtAws/MetaData.pm
    version: 0
  App::MtAws::ParentWorker:
    file: lib/App/MtAws/ParentWorker.pm
    version: 0
  App::MtAws::ProxyTask:
    file: lib/App/MtAws/ProxyTask.pm
    version: 0
  App::MtAws::RetrievalDownloadJob:
    file: lib/App/MtAws/RetrievalDownloadJob.pm
    version: 0
  App::MtAws::RetrievalFetchJob:
    file: lib/App/MtAws/RetrievalFetchJob.pm
    version: 0
  App::MtAws::RetrieveCommand:
    file: lib/App/MtAws/RetrieveCommand.pm
    version: 0
  App::MtAws::RetrieveInventoryJob:
    file: lib/App/MtAws/RetrieveInventoryJob.pm
    version: 0
  App::MtAws::Task:
    file: lib/App/MtAws/Task.pm
    version: 0
  App::MtAws::TreeHash:
    file: lib/App/MtAws/TreeHash.pm
    version: 0
  App::MtAws::Utils:
    file: lib/App/MtAws/Utils.pm
    version: 0
requires:
  Digest::SHA: 0
  JSON::XS: 0
  LWP::Protocol::https: 0
  LWP::UserAgent: 6
  perl: v5.8.8
resources:
  bugtracker: https://github.com/vsespb/mt-aws-glacier/issues
  license: http://www.gnu.org/licenses/gpl-3.0.txt
  repository: https://github.com/vsespb/mt-aws-glacier
version: 0.957
