---
abstract: 'mt-aws/glacier - Perl Multithreaded Multipart sync to Amazon Glacier'
author:
  - 'Victor Efimov <vs@vs-dev.com>'
build_requires:
  B: 0
  Data::Dumper: 0
  DateTime: 0
  HTTP::Daemon: 1.36
  Module::Build: 0.36
  Scalar::Util: 1.11
  TAP::Harness: 0
  Test::Deep: 0.092
  Test::MockModule: 0
  Test::More: 0.88
  Test::Simple: 0.88
  Test::Spec: 0
  Test::Tabs: 0.003
  Time::HiRes: 0
  URI: 1.10
  open: 0
configure_requires:
  Module::Build: 0.36
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132661'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-MtAws
provides:
  App::MtAws:
    file: lib/App/MtAws.pm
    version: 1.056_1
  App::MtAws::ChildWorker:
    file: lib/App/MtAws/ChildWorker.pm
    version: 1.056_1
  App::MtAws::Command::CheckLocalHash:
    file: lib/App/MtAws/Command/CheckLocalHash.pm
    version: 1.056_1
  App::MtAws::Command::DownloadInventory:
    file: lib/App/MtAws/Command/DownloadInventory.pm
    version: 1.056_1
  App::MtAws::Command::Retrieve:
    file: lib/App/MtAws/Command/Retrieve.pm
    version: 1.056_1
  App::MtAws::Command::Sync:
    file: lib/App/MtAws/Command/Sync.pm
    version: 1.056_1
  App::MtAws::ConfigDefinition:
    file: lib/App/MtAws/ConfigDefinition.pm
    version: 1.056_1
  App::MtAws::ConfigEngine:
    file: lib/App/MtAws/ConfigEngine.pm
    version: 1.056_1
  App::MtAws::Exceptions:
    file: lib/App/MtAws/Exceptions.pm
    version: 1.056_1
  App::MtAws::FileVersions:
    file: lib/App/MtAws/FileVersions.pm
    version: 1.056_1
  App::MtAws::Filter:
    file: lib/App/MtAws/Filter.pm
    version: 1.056_1
  App::MtAws::ForkEngine:
    file: lib/App/MtAws/ForkEngine.pm
    version: 1.056_1
  App::MtAws::GlacierRequest:
    file: lib/App/MtAws/GlacierRequest.pm
    version: 1.056_1
  App::MtAws::HttpFileWriter:
    file: lib/App/MtAws/HttpSegmentWriter.pm
    version: 1.056_1
  App::MtAws::HttpMemoryWriter:
    file: lib/App/MtAws/HttpSegmentWriter.pm
    version: 1.056_1
  App::MtAws::HttpSegmentWriter:
    file: lib/App/MtAws/HttpSegmentWriter.pm
    version: 1.056_1
  App::MtAws::HttpWriter:
    file: lib/App/MtAws/HttpSegmentWriter.pm
    version: 1.056_1
  App::MtAws::IntermediateFile:
    file: lib/App/MtAws/IntermediateFile.pm
    version: 1.056_1
  App::MtAws::Job:
    file: lib/App/MtAws/Job.pm
    version: 1.056_1
  App::MtAws::Job::CreateVault:
    file: lib/App/MtAws/Job/CreateVault.pm
    version: 1.056_1
  App::MtAws::Job::DeleteVault:
    file: lib/App/MtAws/Job/DeleteVault.pm
    version: 1.056_1
  App::MtAws::Job::FileCreate:
    file: lib/App/MtAws/Job/FileCreate.pm
    version: 1.056_1
  App::MtAws::Job::FileFinish:
    file: lib/App/MtAws/Job/FileFinish.pm
    version: 1.056_1
  App::MtAws::Job::FileListDelete:
    file: lib/App/MtAws/Job/FileListDelete.pm
    version: 1.056_1
  App::MtAws::Job::FileListRetrieval:
    file: lib/App/MtAws/Job/FileListRetrieval.pm
    version: 1.056_1
  App::MtAws::Job::FileUpload:
    file: lib/App/MtAws/Job/FileUpload.pm
    version: 1.056_1
  App::MtAws::Job::FileVerifyAndUpload:
    file: lib/App/MtAws/Job/FileVerifyAndUpload.pm
    version: 1.056_1
  App::MtAws::Job::InventoryDownload:
    file: lib/App/MtAws/Job/InventoryDownload.pm
    version: 1.056_1
  App::MtAws::Job::InventoryFetch:
    file: lib/App/MtAws/Job/InventoryFetch.pm
    version: 1.056_1
  App::MtAws::Job::RetrievalDownload:
    file: lib/App/MtAws/Job/RetrievalDownload.pm
    version: 1.056_1
  App::MtAws::Job::RetrievalFetch:
    file: lib/App/MtAws/Job/RetrievalFetch.pm
    version: 1.056_1
  App::MtAws::Job::RetrieveInventory:
    file: lib/App/MtAws/Job/RetrieveInventory.pm
    version: 1.056_1
  App::MtAws::Job::SegmentDownload:
    file: lib/App/MtAws/Job/SegmentDownload.pm
    version: 1.056_1
  App::MtAws::Job::SingleDownload:
    file: lib/App/MtAws/Job/SingleDownload.pm
    version: 1.056_1
  App::MtAws::JobIteratorProxy:
    file: lib/App/MtAws/JobIteratorProxy.pm
    version: 1.056_1
  App::MtAws::JobListProxy:
    file: lib/App/MtAws/JobListProxy.pm
    version: 1.056_1
  App::MtAws::JobProxy:
    file: lib/App/MtAws/JobProxy.pm
    version: 1.056_1
  App::MtAws::Journal:
    file: lib/App/MtAws/Journal.pm
    version: 1.056_1
  App::MtAws::LineProtocol:
    file: lib/App/MtAws/LineProtocol.pm
    version: 1.056_1
  App::MtAws::MetaData:
    file: lib/App/MtAws/MetaData.pm
    version: 1.056_1
  App::MtAws::ParentWorker:
    file: lib/App/MtAws/ParentWorker.pm
    version: 1.056_1
  App::MtAws::ParentWorkerNew:
    file: lib/App/MtAws/ParentWorkerNew.pm
    version: 1.056_1
  App::MtAws::ProxyTask:
    file: lib/App/MtAws/ProxyTask.pm
    version: 1.056_1
  App::MtAws::QueueEngine:
    file: lib/App/MtAws/QueueEngine.pm
    version: 1.056_1
  App::MtAws::QueueJob:
    file: lib/App/MtAws/QueueJob.pm
    version: 1.056_1
  App::MtAws::QueueJob::CreateVault:
    file: lib/App/MtAws/QueueJob/CreateVault.pm
    version: 1.056_1
  App::MtAws::QueueJob::Delete:
    file: lib/App/MtAws/QueueJob/Delete.pm
    version: 1.056_1
  App::MtAws::QueueJob::DeleteVault:
    file: lib/App/MtAws/QueueJob/DeleteVault.pm
    version: 1.056_1
  App::MtAws::QueueJob::DownloadInventory:
    file: lib/App/MtAws/QueueJob/DownloadInventory.pm
    version: 1.056_1
  App::MtAws::QueueJob::FetchAndDownloadInventory:
    file: lib/App/MtAws/QueueJob/FetchAndDownloadInventory.pm
    version: 1.056_1
  App::MtAws::QueueJob::Iterator:
    file: lib/App/MtAws/QueueJob/Iterator.pm
    version: 1.056_1
  App::MtAws::QueueJob::MultipartCreate:
    file: lib/App/MtAws/QueueJob/MultipartCreate.pm
    version: 1.056_1
  App::MtAws::QueueJob::MultipartFinish:
    file: lib/App/MtAws/QueueJob/MultipartFinish.pm
    version: 1.056_1
  App::MtAws::QueueJob::MultipartPart:
    file: lib/App/MtAws/QueueJob/MultipartPart.pm
    version: 1.056_1
  App::MtAws::QueueJob::RetrieveInventory:
    file: lib/App/MtAws/QueueJob/RetrieveInventory.pm
    version: 1.056_1
  App::MtAws::QueueJob::Upload:
    file: lib/App/MtAws/QueueJob/Upload.pm
    version: 1.056_1
  App::MtAws::QueueJob::UploadMultipart:
    file: lib/App/MtAws/QueueJob/UploadMultipart.pm
    version: 1.056_1
  App::MtAws::QueueJob::Verify:
    file: lib/App/MtAws/QueueJob/Verify.pm
    version: 1.056_1
  App::MtAws::QueueJob::VerifyAndUpload:
    file: lib/App/MtAws/QueueJob/VerifyAndUpload.pm
    version: 1.056_1
  App::MtAws::QueueJobResult:
    file: lib/App/MtAws/QueueJobResult.pm
    version: 1.056_1
  App::MtAws::Task:
    file: lib/App/MtAws/Task.pm
    version: 1.056_1
  App::MtAws::TreeHash:
    file: lib/App/MtAws/TreeHash.pm
    version: 1.056_1
  App::MtAws::Utils:
    file: lib/App/MtAws/Utils.pm
    version: 1.056_1
recommends:
  LWP::Protocol::https: 6
requires:
  Carp: 0
  Digest::SHA: 0
  Encode: 0
  Exporter: 0
  File::Basename: 0
  File::Find: 0
  File::Path: 0
  File::Spec: 0
  File::Temp: 0.16
  File::stat: 0
  FindBin: 0
  Getopt::Long: 2.24
  HTTP::Request: 0
  I18N::Langinfo: 0
  IO::Handle: 0
  IO::Pipe: 0
  IO::Select: 0
  JSON::XS: 1
  LWP: 5.803
  List::Util: 1.11
  POSIX: 0
  PerlIO::encoding: 0
  Time::Local: 0
  Time::localtime: 0
  bytes: 0
  constant: 0
  integer: 0
  lib: 0
  perl: 5.008008
  strict: 0
  utf8: 0
  warnings: 0
resources:
  bugtracker: https://github.com/vsespb/mt-aws-glacier/issues
  homepage: http://mt-aws.com/
  license: http://www.gnu.org/licenses/gpl-3.0.txt
  repository: https://github.com/vsespb/mt-aws-glacier
version: 1.056_1
